blank_issues_enabled: true
contact_links:
    - name: Agentic Wiki Discussions
      url: https://github.com/fine405/vsc-extension-agentic-wiki/discussions
      about: Please ask and answer questions here.
